<?php
require_once __DIR__ . '/config/config.php';
require_once __DIR__ . '/config/database.php';
$info=get_personal_info();$skills=get_portfolio_skills();$experiences=get_portfolio_experiences();$projects=get_portfolio_projects();$education=get_portfolio_education();$certifications=get_portfolio_certifications();
require_once __DIR__ . '/includes/header.php';
require_once __DIR__ . '/includes/navbar.php';
?>
<section id="home" class="hero"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-7"><span class="section-subtitle">PHP Developer Portfolio</span><h1 class="display-3 fw-bold mt-2">Hi, I'm <span class="text-gradient"><?php echo htmlspecialchars($info['full_name']); ?></span></h1><h3 id="typingText" class="text-info my-3">Junior PHP Developer</h3><p class="lead text-muted"><?php echo htmlspecialchars($info['tagline']); ?></p><div class="d-flex flex-wrap gap-3 mt-4"><a class="btn-primary-custom" href="#projects"><i class="fas fa-code"></i> View Projects</a><a class="btn-outline-custom" href="#contact"><i class="fas fa-paper-plane"></i> Contact Me</a><a class="btn-outline-custom" target="_blank" href="<?php echo htmlspecialchars($info['github_url']); ?>"><i class="fab fa-github"></i> GitHub</a></div></div><div class="col-lg-5"><div class="hero-card p-4"><h4 class="fw-bold">Developer Profile</h4><p class="text-muted mb-2"><i class="fas fa-map-marker-alt text-info me-2"></i><?php echo htmlspecialchars($info['location']); ?></p><p class="text-muted mb-2"><i class="fas fa-briefcase text-info me-2"></i><?php echo htmlspecialchars($info['role']); ?></p><p class="text-muted mb-0"><i class="fas fa-circle-check text-info me-2"></i><?php echo htmlspecialchars($info['availability']); ?></p></div></div></div></div></section>
<section id="about" class="py-5"><div class="container py-4"><span class="section-subtitle">About</span><h2 class="section-title">About <span class="text-gradient">Me</span></h2><div class="glass-card mt-4"><p class="text-muted mb-0"><?php echo sanitize_html_styles($info['bio']); ?></p></div></div></section>
<section id="skills" class="py-5"><div class="container py-4"><span class="section-subtitle">Skills</span><h2 class="section-title">Technical <span class="text-gradient">Stack</span></h2><div class="d-flex flex-wrap gap-2 mt-4"><?php foreach($skills as $s): ?><div class="skill-chip"><i class="<?php echo htmlspecialchars($s['icon_class']); ?> text-info me-2"></i><?php echo htmlspecialchars($s['name']); ?></div><?php endforeach; ?></div></div></section>
<section id="experience" class="py-5"><div class="container py-4"><span class="section-subtitle">Experience</span><h2 class="section-title">Work <span class="text-gradient">Experience</span></h2><div class="mt-4"><?php foreach($experiences as $e): ?><div class="timeline-item"><h5 class="fw-bold mb-1"><?php echo htmlspecialchars($e['role']); ?></h5><div class="text-info fw-semibold"><?php echo htmlspecialchars($e['company']); ?></div><small class="text-muted"><?php echo htmlspecialchars($e['duration']); ?></small><?php $r=is_array($e['responsibilities'])?$e['responsibilities']:json_decode($e['responsibilities'],true); if(is_array($r)): ?><ul class="text-muted mt-2"><?php foreach($r as $x): ?><li><?php echo htmlspecialchars($x); ?></li><?php endforeach; ?></ul><?php endif; ?></div><?php endforeach; ?></div></div></section>
<section id="projects" class="py-5"><div class="container py-4"><span class="section-subtitle">Projects</span><h2 class="section-title">Featured <span class="text-gradient">Projects</span></h2><div class="row g-4 mt-2"><?php foreach($projects as $p): ?><div class="col-md-6 col-lg-4 project-item" data-category="<?php echo htmlspecialchars($p['category']); ?>"><div class="project-card h-100"><img src="<?php echo get_project_image_url($p['thumbnail']); ?>" alt="<?php echo htmlspecialchars($p['title']); ?>"><span class="tech-tag"><?php echo htmlspecialchars($p['category']); ?></span><h5 class="fw-bold mt-3"><?php echo htmlspecialchars($p['title']); ?></h5><p class="text-muted small"><?php echo htmlspecialchars($p['short_description']); ?></p><div class="mb-3"><?php foreach(array_slice(array_map('trim',explode(',',$p['technologies'])),0,4) as $t): ?><span class="tech-tag me-1 mb-1"><?php echo htmlspecialchars($t); ?></span><?php endforeach; ?></div><a class="btn-outline-custom btn-sm" href="project-detail.php?id=<?php echo (int)$p['id']; ?>">View Details</a></div></div><?php endforeach; ?></div></div></section>
<section id="education" class="py-5"><div class="container py-4"><span class="section-subtitle">Education</span><h2 class="section-title">Education & <span class="text-gradient">Training</span></h2><div class="row g-4 mt-2"><?php foreach($education as $e): ?><div class="col-md-6"><div class="glass-card h-100"><h5 class="fw-bold"><?php echo htmlspecialchars($e['degree']); ?></h5><div class="text-info"><?php echo htmlspecialchars($e['institution']); ?></div><p class="text-muted small mb-0"><?php echo htmlspecialchars($e['status']); ?> · <?php echo htmlspecialchars($e['start_year']); ?> - <?php echo htmlspecialchars($e['end_year']); ?></p></div></div><?php endforeach; ?></div></div></section>
<section id="certifications" class="py-5"><div class="container py-4"><span class="section-subtitle">Certifications</span><h2 class="section-title">Courses & <span class="text-gradient">Certificates</span></h2><div class="row g-3 mt-2"><?php foreach($certifications as $c): ?><div class="col-md-6"><div class="glass-card h-100"><h6 class="fw-bold mb-1"><?php echo htmlspecialchars($c['title']); ?></h6><small class="text-muted"><?php echo htmlspecialchars($c['issuing_organization']); ?></small></div></div><?php endforeach; ?></div></div></section>
<section id="services" class="py-5"><div class="container py-4"><span class="section-subtitle">Services</span><h2 class="section-title">What I <span class="text-gradient">Build</span></h2><div class="row g-4 mt-2"><?php $services=[['fa-code','PHP Development'],['fa-fire','CodeIgniter MVC'],['fa-user-shield','Admin Panels'],['fa-database','MySQL Databases'],['fa-bug','Bug Fixing'],['fa-network-wired','API Integration'],['fa-mobile-alt','Responsive Web UI'],['fa-sync-alt','Website Maintenance']];foreach($services as $s): ?><div class="col-md-6 col-lg-3"><div class="service-card h-100"><div class="service-icon mb-3"><i class="fas <?php echo $s[0]; ?>"></i></div><h5 class="fw-bold"><?php echo $s[1]; ?></h5></div></div><?php endforeach; ?></div></div></section>
<section id="contact" class="py-5"><div class="container py-4"><span class="section-subtitle">Contact</span><h2 class="section-title">Get In <span class="text-gradient">Touch</span></h2><div class="row g-4 mt-2"><div class="col-lg-5"><div class="glass-card"><p class="text-muted">Have a job opportunity, freelance project or collaboration proposal? Send me a message.</p><p><i class="fas fa-map-marker-alt text-info me-2"></i><?php echo htmlspecialchars($info['location']); ?></p><a target="_blank" class="btn-outline-custom" href="<?php echo htmlspecialchars($info['github_url']); ?>"><i class="fab fa-github"></i> GitHub Profile</a></div></div><div class="col-lg-7"><div class="contact-form-card"><div id="contactFormAlert" style="display:none"></div><form id="contactForm"><input type="hidden" name="csrf_token" value="<?php echo htmlspecialchars(get_csrf_token()); ?>"><div class="row g-3"><div class="col-md-6"><input class="form-control form-control-custom" name="name" placeholder="Your name" required></div><div class="col-md-6"><input type="email" class="form-control form-control-custom" name="email" placeholder="Email" required></div><div class="col-md-6"><input class="form-control form-control-custom" name="phone" placeholder="Phone" required></div><div class="col-md-6"><input class="form-control form-control-custom" name="subject" placeholder="Subject" required></div><div class="col-12"><textarea class="form-control form-control-custom" name="message" rows="5" placeholder="Message" required></textarea></div><div class="col-12"><button class="btn-primary-custom w-100 justify-content-center" type="submit">Send Message <i class="fas fa-paper-plane"></i></button></div></div></form></div></div></div></div></section>
<?php require_once __DIR__ . '/includes/project_modal.php'; require_once __DIR__ . '/includes/footer.php'; ?>
